name: Run Mobile Automation
#on: [push, pull_request]
on:
   workflow_dispatch:
    inputs:
      platform:
        description: 'select where to run'
        required: true
        default: 'github'
        type: choice
        options:
        - github
      artifacts:
        description: 'Artifact reporting'
        required: false
        type: boolean
    push:
      branches:
      - main

jobs:
  setup-build-test:
    runs-on: macos-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Set up JDK 1.8
          uses: actions/setup-java@v1
          with:
            java-version: 1.8
        - name: Setup Appium Server
          run: |
            chmod +x ./RunAppiumServer.sh
            ./RunAppiumServer.sh
        - name: Install and Setup emulator
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 27
            script: emulator -avd avd28 -no-audio -no-window -no-accel &
        - name: Install Dependencies
          run: npm install
        - name: Run Automation
          run: npm run test