name: Run Mobile Automation
#on: [push, pull_request]
on:
   workflow_dispatch:
    inputs:
      platform:
        description: 'select where to run'
        required: true
        default: 'github'
        type: choice
        options:
        - github
      artifacts:
        description: 'Artifact reporting'
        required: false
        type: boolean
    push:
      branches:
      - main

jobs:
  setup-build-test:
    runs-on: macos-13
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup JDK
          uses: actions/setup-java@v4
          with:
            distribution: 'temurin'
            java-version: 17
        - name: Setup Node JS
          uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install Appium and Setup Appium Server
          run: |
            chmod +x ./RunAppiumServer.sh
            ./RunAppiumServer.sh
        - name: Install Dependencies
          run: | 
            npx npm-check-updates -u
            npm install
        - name: Run Automation Test
          uses: reactivecircus/android-emulator-runner@v2
          with:
            api-level: 29
            force-avd-creation: false
            emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
            disable-animations: true
            script: npm run test
        - name: Generate Report
          uses: actions/upload-artifact@v3
          with:
            name: timeline-report
            path: ./timeline-report