name: Run Mobile Automation
#on: [push, pull_request]
on:
   workflow_dispatch:
    inputs:
      platform:
        description: 'select where to run'
        required: true
        default: 'github'
        type: choice
        options:
        - github
      artifacts:
        description: 'Artifact reporting'
        required: false
        type: boolean
    push:
      branches:
      - main

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [25] 
        target: [default]
    steps:
        - name: Checkout
          uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install emulator
          uses: reactivecircus/android-emulator-runner@v1
          with:
            api-level: ${{ matrix.api-level }}
            target: ${{ matrix.target }}
            arch: x86_64
            profile: Nexus 6
        - name: Setup Appium Server
          run: chmod +x ./RunAppiumServer.sh
        - name: Install Dependencies
          run: npm install
        - name: Run Automation
          run: npx wdio
          continue-on-error: false